/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Room = (props) => {
const { nodes, materials } = useGLTF('/assets/models/Goldmund_Sphere_Szene.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[2.357, 1.479, 2.357]} scale={1.215}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere004.geometry}
          material={materials['Goldmund Sphere.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere004_1.geometry}
          material={materials['Emission.002']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath.geometry}
        material={nodes.NurbsPath.material}
        rotation={[2.807, -0.315, 2.221]}
        scale={[0.454, 0.408, 0.408]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={nodes.Text.material}
        position={[-1.307, 0.478, 2.988]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={nodes.Plane002.material}
        position={[1.058, 1.174, -1.86]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.068}
      />
    </group>
  )
}

useGLTF.preload('/assets/models/Goldmund_Sphere_Szene.glb')





 export default Room