/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Room = (props) => {
  const { nodes, materials } = useGLTF('/NarzissCube.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]} rotation={[-0.238, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials['Narziss Cube']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials['Emission.001']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/NarzissCube.glb')

 export default Room